---
permalink: reference-smb-share-size-dropping-to-0-in-scvmm.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= El tamaño de los recursos compartidos de SMB desciende a 0 en SCVMM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Edición*
+
El tamaño de recurso compartido de SMB 3.0 nuevo o existente puede caer a 0 en System Center Virtual Machine Manager (SCVMM).

* *Causa*
+
Si la reinicialización de cuota tarda mucho tiempo en ONTAP debido a una gran cantidad de I/O, el tamaño del recurso compartido de SMB 3,0 nuevo o existente puede reducirse a 0 en SCVMM. Cuando se produce este problema, no es posible aprovisionar nuevas máquinas virtuales en recursos compartidos SMB 3,0 nuevos o existentes.

* *Acción Correctiva*
+
.. Desactivar las cuotas.
.. Agregue una regla de cuota predeterminada del tipo «'tree'» en cada volumen que aloje recursos compartidos de SMB.
.. Active las cuotas de esos volúmenes a los que se agregó una regla de cuota predeterminada y reinicie SMI-S Provider.



