---
permalink: reference-total-managed-space-for-a-storage-pool-aggregate-discrepancy.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= Discrepancia de espacio administrado total para un pool de almacenamiento (volumen)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
El espacio total gestionado que muestra NetApp SMI-S Provider para un grupo de almacenamiento (volumen) puede diferir del tamaño que indican otras herramientas de gestión de almacenamiento, como FilerView, ya que SMI-S Provider incluye la reserva de WAFL y de snapshot. Esta discrepancia es un comportamiento esperado y no requiere ninguna medida correctiva.

* *Edición*
+
Si utiliza otra herramienta de gestión del almacenamiento, como FilerView, es posible que observe un tamaño diferente indicado para el espacio gestionado total de un pool de almacenamiento (volumen) que el tamaño devuelto por SMI-S Provider.

* *Causa*
+
Esta discrepancia se produce debido a que el tamaño que devuelve SMI-S Provider incluye la reserva WAFL y Snapshot, mientras que FilerView y otras herramientas sólo muestran el espacio utilizable, excluye la reserva WAFL y Snapshot.

* *Acción Correctiva*
+
Este es un comportamiento esperado; no hay acción correctiva.


