---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: Antes de instalar SMI-S Provider, debe verificar que el host Windows esté ejecutando un sistema operativo compatible. 
---
= Versiones de sistemas operativos compatibles
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
Le recomendamos que instale SMI-S Provider en su propia máquina virtual (VM) de Windows dedicada. Esta máquina virtual puede estar en el mismo dominio para permitir una administración segura y conveniente.

Antes de instalar SMI-S Provider, debe verificar que el host Windows esté ejecutando un sistema operativo compatible.

[cols="3*"]
|===
| De NetApp | Versiones compatibles | Software cliente necesario 


 a| 
Windows
 a| 
* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

 a| 
Las bibliotecas de tiempo de ejecución de Microsoft Visual C{pp} 2010 se instalan automáticamente durante la instalación del proveedor SMI-S. Para evitar posibles problemas relacionados con las bibliotecas de tiempo de ejecución, debe instalar Microsoft Visual C{pp} 2010 Redistributable Package (x86) desde la siguiente ubicación: http://www.microsoft.com[]

|===


== Asegúrese de que el equipo host del proveedor cumpla con las especificaciones

Para ejecutar SMI-S Provider, la máquina host del proveedor debe cumplir las siguientes especificaciones:

* El proveedor no se puede instalar directamente en un nodo Hyper-V. En su lugar, puede instalarlo en una máquina virtual Hyper-V.
* El System Center Virtual Machine Manager (SCVMM) no debe estar ejecutándose en la máquina host del proveedor.
* El equipo host del proveedor no debe ejecutar otros programas que requieran mucha memoria.
* El equipo host del proveedor no debe ejecutar proveedores SMI-S de ningún otro proveedor.

