---
permalink: reference-possible-errors-when-loading-shared-libraries.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= Posibles errores al cargar bibliotecas compartidas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
* *Mensajes*
+
`Error while loading shared libraries: libssl.so 1.0.0: cannot open shared object file: No such file or directory.`

+
La `smis cimserver` el estado muestra que el cimserver se está ejecutando correctamente, pero el resto `/usr/netapp/smis/pegasus/bin/cim` los comandos muestran varios mensajes de error.

+
Por ejemplo, puede recibir el mensaje `cimserver not running` al ejecutar el `cimserver`o puede que reciba el mensaje `/usr/netapp/smis/pegasus/bin/ cimcli: symbol lookup error: /usr/netapp/smis/pegasus/bin/cimcli: undefined symbol: _ZN7Pegasus16StringConversion21decimalStringToUint64EPKcRy` al ejecutar cimcli. Estos ejemplos no son de todo incluido.

* *Descripción*
+
Este mensaje (y mensajes similares) se produce cuando el `LD_LIBRARY_PATH` el entorno no está establecido en el directorio de instalación.

* *Acción Correctiva*
+
Escriba uno de los siguientes comandos para configurar el `LD_LIBRARY_PATH` variable de entorno al directorio de instalación:



`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/netapp/smis/pegasus/lib`

`setenv LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/netapp/smis/pegasus/lib`
