---
permalink: reference-cannot-connect-to-localhost-5988-error.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= No se puede conectar con localhost:5988
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Mensaje*
+
`Cannot connect to localhost:5988. Connection failed. Trying to connect to localhost:5988`

* *Descripción*
+
Este mensaje aparece cuando las conexiones HTTPS están desactivadas o el puerto HTTPS no está establecido en 5988, o si el proveedor ha dejado de funcionar y permanece en el estado de clasificación.

* *Acción Correctiva*
+
Compruebe que los valores de `enableHttpsConnection` y.. `httpsPort` son correctas:

+
`cimconfig -g enableHttpConnection`

+
`cimconfig -g enableHttpsConnection`

+
`cimconfig -g httpPort`

+
`cimconfig -g httpsPort`

+
Si `enableHttpConnection` o. `enableHttpsConnection` no está establecido en `true`, escriba los siguientes comandos:

+
`cimconfig -s enableHttpConnection -p`

+
`smis cimserver restart`

+
Si `httpPort` no está establecido en 5988, introduzca los siguientes comandos:

+
`cimconfig -s httpPort=5988 -p`

+
`smis cimserver restart`

+
Si el proveedor ha dejado de funcionar y permanece en el estado de presentación en paneles, abra el Administrador de tareas y finalice el proceso y, a continuación, reinicie el proveedor.


