---
permalink: reference-clone-snapshot-operations-are-not-allowed.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= No se permiten las operaciones de clonado/Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Es posible que aparezca un error indicando que no se permiten operaciones de clon o de copia de snapshot mientras se está llevando a cabo una operación de división de clon LUN. Espera a que finalice la división de clon LUN y luego vuelve a intentar la operación.

* *Mensaje*
+
`Clone/Snapshot operations are not allowed while LUN clone split operations are going on in the volume. Please wait for some time and try again.`

* *Descripción*
+
Este error ocurre si se intentan ejecutar operaciones de Snapshot durante una división de clones de la LUN. No se pueden realizar operaciones de Snapshot en un volumen donde se está dividir una LUN si esa división de clones de la LUN se ejecuta en segundo plano.

* *Acción Correctiva*
+
Pruebe las operaciones de Snapshot después de dividir la LUN.


