---
permalink: reference-no-ontap-element-in-response-error.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= Retorno de archivador: No hay elemento ONTAP como respuesta
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
El mensaje  `Filer return: No ontap element in response` ocurre cuando una llamada a la API de ONTAP realizada por NetApp SMI-S Provider agota el tiempo de espera. Aumenta el valor del tiempo de espera para resolver este problema.

* *Mensaje*
+
`Filer return: No ontap element in response`.

* *Descripción*
+
Este mensaje se produce cuando se agota el tiempo de espera de la llamada a la API de ONTAP. El tiempo de espera predeterminado de la llamada a la API de ONTAP es de 60 segundos, lo que podría ser demasiado corto en algunos casos.

* *Acción Correctiva*
+
Cambie el tiempo de espera de la llamada API de ONTAP a un valor superior a 60 segundos. Para ello, configure la variable de entorno `ONTAPI_TIMEOUT_SEC` y, a continuación, reinicie SMI-S. Provider.


