---
permalink: reference-entering-passwords-containing-special-characters.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= Problema al introducir contraseñas que contengan caracteres especiales
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Edición*
+
En los sistemas operativos en inglés, utilizando una contraseña que contiene caracteres especiales con el `smis` El comando no funciona en un entorno de Windows. Este problema no se ha probado con sistemas operativos que no están en inglés.

* *Causa*
+
En Windows, los siguientes caracteres, más cualquier espacio, se consideran caracteres especiales y provocan un error en la entrada de la contraseña si la contraseña no está entre comillas:

+
, & ' < > ; | = {caret} "

* *Acción Correctiva*
+
Si una contraseña contiene espacios o caracteres especiales, escríbala entre comillas dobles (" ") cuando la utilice en el `smis` comando. Tenga en cuenta que el carácter de presupuesto (") es un carácter especial y que nunca se debe utilizar en la contraseña.





== Emitir contraseñas con caracteres especiales

`smis add 1.2.3.4 Administrator "pass word"`

`smis add 1.2.3.4 Administrator "pass&word"`
