---
permalink: reference-cannot-add-a-storage-system-using-a-nondefault-http-or-https-port.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= No se puede añadir un sistema de almacenamiento mediante un puerto HTTP o HTTPS no predeterminado
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Edición*
+
No puede añadir un sistema de almacenamiento que ejecute HTTP o HTTPS en un puerto no predeterminado.

* *Causa*
+
De forma predeterminada, SMI-S Provider de NetApp utiliza el puerto 80 para comunicarse con los sistemas de almacenamiento a través de HTTP y el puerto 443 para comunicarse a través de HTTPS.

* *Acción Correctiva*
+
Utilice el siguiente comando para añadir un sistema de almacenamiento que utilice un puerto distinto de 80 para el tráfico HTTP o el puerto 443 para el tráfico HTTPS:

+
`cimcli ci -n root/ontap ONTAP_FilerData hostName=_storage_sys_ip_address_ port=_non_default_port_ userName=_storage_sys_user_ password=_storage_sys_pwd_ comMechanism=HTTP -u _agent_user_ -p _agent_pwd_-llocalhost:5989 -s`

+
`-u`, `-p`, `-l`, y. `-s` son parámetros opcionales.





== Añadir un sistema de almacenamiento que utilice el puerto 8000 para el tráfico HTTP

`cimcli ci -n root/ontap ONTAP_FilerData hostName=10.60.167.12 port=8000 userName=root password=netapp1! comMechanism=HTTP -u root -p netapp1! -l localhost:5989 -s --timeout 180`
