---
permalink: reference-warning-26130.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados con el proveedor SMI-S de NetApp. 
---
= Advertencia 26130
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La advertencia 26130 se produce cuando se asigna capacidad de almacenamiento a un grupo de hosts en el que ninguno de los hosts tiene acceso a la matriz de almacenamiento, lo que impide colocar máquinas virtuales en el sistema de almacenamiento. Concede el acceso necesario a cada host para resolver esta advertencia.



[[message]]
== Mensaje

`Warning (26130) Storage pool has been allocated to host group where none of hosts in host group has access to storage array.`



[[description]]
== Descripción

Este error se produce cuando se asigna capacidad de almacenamiento y se otorga acceso a una cabina a los hosts que están en un grupo de hosts. Con esta advertencia, es imposible poner los equipos virtuales en los sistemas de almacenamiento.



[[corrective-action]]
== Acción correctiva

. En cada equipo host, añada la dirección IP de cada sistema de almacenamiento a la aplicación iSCSI Initiator.
. Si es necesario, en cada sistema de almacenamiento, para cada máquina host, cree un igroup único vinculado con el nombre de nodo iSCSI correspondiente de la máquina host correspondiente.
. Para cada equipo host conectado a ONTAP, abra la aplicación MPIO y añada el siguiente ID de hardware:
+
** Para ONTAP, introduzca `*NETAPP LUN C-Mode*`.


. Reinicie las máquinas host.
. Retire el proveedor.
. Vuelva a establecer el pool de almacenamiento.

