---
permalink: task-generate-a-self-signed-certificate-for-the-cim-server-windows.html 
sidebar: sidebar 
keywords: ssl authentication, enable, cim server, installation, self-signed certificate 
summary: De forma predeterminada, la autenticación SSL está habilitada para el servidor CIM. Durante la instalación del proveedor SMI-S, se instala un certificado autofirmado para el servidor CIM en el directorio pegasus. Puede generar su propio certificado autofirmado y usarlo en lugar de utilizar el certificado predeterminado. 
---
= Genere un certificado autofirmado para el servidor CIM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
De forma predeterminada, la autenticación SSL está habilitada para el servidor CIM. Durante la instalación del proveedor SMI-S, se instala un certificado autofirmado para el servidor CIM en el `pegasus` directorio. Debe generar su propio certificado autofirmado en lugar de utilizar el certificado predeterminado.


CAUTION: Cuando instala el proveedor SMI-S, el certificado autofirmado predeterminado que se instala queda desactualizado. Como resultado, la conexión SSL al proveedor SMI-S falla desde *Agregar dispositivos de almacenamiento* en System Center Virtual Machine Manager (SCVMM). Debe generar un certificado autofirmado para el servidor CIM y luego reiniciar el servicio del proveedor SMI-S. Para obtener más información, consulte link:https://kb.netapp.com/data-mgmt/SMI-S/SMI-S_Issues/CSMIS-3["Artículo de la base de conocimientos de NetApp : "CSMIS-3: cimom.cert en NetApp SMI-S Provider 5.2.7 vence en el momento de la instalación"."^]

.Antes de empezar
* Ya debe haber iniciado sesión como administrador.
* Ya debe haber accedido a SMI-S Provider.
* Debes haber descargado e instalado OpenSSL en tu host Windows.


.Pasos
. Descargue el `openssl.cnf` archivo desde la siguiente ubicación: link:http://web.mit.edu/crypto/openssl.cnf["http://web.mit.edu/crypto/openssl.cnf"^]
. Mueva el `openssl.cnf` archivo en el directorio bin:
+
`*%PEGASUS_HOME%\bin\openssl.cnf*`

. Ajuste la `OPENSSL_CONF` variable ambiental a la ubicación del `openssl.cnf` archivo:
+
`*C:\ >set OPENSSL_CONF=%PEGASUS_HOME%\bin\openssl.cnf*`

+
Esto sólo define la variable de entorno durante la sesión actual del símbolo del sistema. Si desea definir permanentemente la variable de entorno, puede utilizar una de las siguientes opciones:

+
** Vaya a *Propiedades > Variables ambientales* y actualice la variable en *Sistema*.
** Utilice el símbolo del sistema para definir permanentemente la variable:
+
`*setx OPENSSL_CONF “%PEGASUS_HOME%\bin\openssl.cnf*`.

+
La variable se define al abrir una nueva sesión de símbolo del sistema.



. Desplácese hasta la `%PEGASUS_HOME%\bin` directorio:
+
`*C:\cd %pegasus_home%\bin*`

. Generar una clave privada:
+
`*openssl genrsa -out cimom.key 2048*`

. Generar una solicitud de certificado:
+
`*openssl req -new -key cimom.key -out cimom.csr*`

. Introduzca la información de la solicitud de certificado cuando se le solicite.
. Genere el certificado autofirmado:
+
`*openssl x509 -in cimom.csr -out cimom.cert -req -signkey cimom.key -days 1095*`

+
Puede proporcionar un número diferente de días para los cuales es válido el certificado.

. Copie el `cimom.key` y.. `cimom.cert` archivos en la `pegasus` directorio (Windows: `C:\Program Files (x86)\NetApp\smis\pegasus`).
. Reinicie el servicio del proveedor SMI-S:
+
`smis cimserver restart`





== Resultado

El intervalo de fechas del certificado comienza en la fecha actual y se ejecuta durante el número de días especificado.
